/**
 * Analyzer Registry — Comprehensive database of all known lab analyzers
 * that can be integrated with PathoLab Pro via ASTM, HL7, or proprietary protocols.
 *
 * Each analyzer defines:
 * - id: unique identifier
 * - brand, model, category
 * - protocol: 'astm' | 'hl7' | 'proprietary'
 * - transport: 'serial' | 'tcp'
 * - serialSettings: default RS232 config
 * - tcpPort: default TCP port (if applicable)
 * - direction: 'uni' (receive only) | 'bi' (bidirectional)
 * - testMapping: maps analyzer test codes to common param names
 */

const ANALYZERS = [
  // ========================== HEMATOLOGY ==========================
  {
    id: 'mindray-bc5300',
    brand: 'Mindray',
    model: 'BC-5300',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR'],
  },
  {
    id: 'mindray-bc5380',
    brand: 'Mindray',
    model: 'BC-5380',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR'],
  },
  {
    id: 'mindray-bc6800',
    brand: 'Mindray',
    model: 'BC-6800',
    category: 'Hematology',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR', 'IG%', 'IG#', 'NRBC#', 'NRBC%'],
  },
  {
    id: 'sysmex-xn1000',
    brand: 'Sysmex',
    model: 'XN-1000',
    category: 'Hematology',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEUT%', 'NEUT#', 'LYMPH%', 'LYMPH#', 'MONO%', 'MONO#', 'EO%', 'EO#', 'BASO%', 'BASO#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR', 'IG%', 'IG#', 'NRBC#', 'NRBC%'],
  },
  {
    id: 'sysmex-xn550',
    brand: 'Sysmex',
    model: 'XN-550',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEUT%', 'NEUT#', 'LYMPH%', 'LYMPH#', 'MONO%', 'MONO#', 'EO%', 'EO#', 'BASO%', 'BASO#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },
  {
    id: 'sysmex-kx21',
    brand: 'Sysmex',
    model: 'KX-21',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#'],
  },
  {
    id: 'sysmex-xp100',
    brand: 'Sysmex',
    model: 'XP-100',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },
  {
    id: 'erba-h560',
    brand: 'Erba',
    model: 'H560',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },
  {
    id: 'erba-h360',
    brand: 'Erba',
    model: 'H360',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#'],
  },
  {
    id: 'beckman-dxh900',
    brand: 'Beckman Coulter',
    model: 'DxH 900',
    category: 'Hematology',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR', 'IG%', 'IG#', 'NRBC#', 'NRBC%'],
  },
  {
    id: 'beckman-act5diff',
    brand: 'Beckman Coulter',
    model: 'AcT 5Diff',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#'],
  },
  {
    id: 'horiba-pentra60',
    brand: 'Horiba',
    model: 'Pentra 60',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-CV', 'PDW', 'MPV'],
  },
  {
    id: 'horiba-yumizen-h500',
    brand: 'Horiba',
    model: 'Yumizen H500',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR'],
  },
  {
    id: 'transasia-xl200',
    brand: 'Transasia',
    model: 'XL 200',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },
  {
    id: 'transasia-xl640',
    brand: 'Transasia',
    model: 'XL 640',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR'],
  },
  {
    id: 'rayto-rt7600',
    brand: 'Rayto',
    model: 'RT-7600',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR'],
  },
  {
    id: 'rayto-rt3900',
    brand: 'Rayto',
    model: 'RT-3900',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },
  {
    id: 'agappe-mispa-count',
    brand: 'Agappe',
    model: 'Mispa Count',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'LYM%', 'LYM#', 'MON%', 'MON#', 'GRA%', 'GRA#'],
  },
  {
    id: 'dymind-dh636',
    brand: 'Dymind',
    model: 'DH-636',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT', 'P-LCR'],
  },
  {
    id: 'genrui-hc5100',
    brand: 'Genrui',
    model: 'HC-5100',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },
  {
    id: 'nikon-kohden-celltac',
    brand: 'Nihon Kohden',
    model: 'Celltac F',
    category: 'Hematology',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['WBC', 'RBC', 'HGB', 'HCT', 'MCV', 'MCH', 'MCHC', 'PLT', 'NEU%', 'NEU#', 'LYM%', 'LYM#', 'MON%', 'MON#', 'EOS%', 'EOS#', 'BAS%', 'BAS#', 'RDW-SD', 'RDW-CV', 'PDW', 'MPV', 'PCT'],
  },

  // ========================== BIOCHEMISTRY ==========================
  {
    id: 'erba-em360',
    brand: 'Erba',
    model: 'EM 360',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA'],
  },
  {
    id: 'erba-em200',
    brand: 'Erba',
    model: 'EM 200',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA'],
  },
  {
    id: 'erba-xl640-biochem',
    brand: 'Erba',
    model: 'XL 640 (Biochem)',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL'],
  },
  {
    id: 'mindray-bs240',
    brand: 'Mindray',
    model: 'BS-240',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'LDH', 'AMYL'],
  },
  {
    id: 'mindray-bs480',
    brand: 'Mindray',
    model: 'BS-480',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c'],
  },
  {
    id: 'mindray-bs820',
    brand: 'Mindray',
    model: 'BS-820',
    category: 'Biochemistry',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO'],
  },
  {
    id: 'roche-cobas-c111',
    brand: 'Roche',
    model: 'Cobas c111',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO', 'C3', 'C4', 'IgG', 'IgA', 'IgM'],
  },
  {
    id: 'roche-cobas-c311',
    brand: 'Roche',
    model: 'Cobas c311',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO', 'C3', 'C4', 'IgG', 'IgA', 'IgM'],
  },
  {
    id: 'roche-cobas-c413',
    brand: 'Roche',
    model: 'Cobas c413',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO'],
  },
  {
    id: 'beckman-au480',
    brand: 'Beckman Coulter',
    model: 'AU480',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP'],
  },
  {
    id: 'beckman-au680',
    brand: 'Beckman Coulter',
    model: 'AU680',
    category: 'Biochemistry',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO', 'C3', 'C4', 'IgG', 'IgA', 'IgM'],
  },
  {
    id: 'siemens-dimension-xpand',
    brand: 'Siemens',
    model: 'Dimension XPand',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'TSH', 'T4', 'T3'],
  },
  {
    id: 'siemens-rxl-max',
    brand: 'Siemens',
    model: 'Dimension RXL Max',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'TSH', 'T4', 'T3', 'PSA', 'AFP', 'CEA', 'CA125', 'CA19-9'],
  },
  {
    id: 'abbott-architect-c4000',
    brand: 'Abbott',
    model: 'Architect c4000',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP'],
  },
  {
    id: 'abbott-architect-c8000',
    brand: 'Abbott',
    model: 'Architect c8000',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO', 'C3', 'C4', 'IgG', 'IgA', 'IgM'],
  },
  {
    id: 'randox-daytona',
    brand: 'Randox',
    model: 'Daytona',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'LDH', 'AMYL'],
  },
  {
    id: 'randox-rx-imola',
    brand: 'Randox',
    model: 'RX Imola',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'CK-MB', 'LDH', 'AMYL', 'LIPA', 'HbA1c', 'CRP', 'RF', 'ASO'],
  },
  {
    id: 'aspen-a200',
    brand: 'Aspen',
    model: 'A-200',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'TG', 'CHOL', 'HDL', 'LDL'],
  },
  {
    id: 'aspen-a400',
    brand: 'Aspen',
    model: 'A-400',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'LDH'],
  },
  {
    id: 'horiba-indiko',
    brand: 'Horiba',
    model: 'Gallery Indiko',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'LDH', 'AMYL'],
  },
  {
    id: 'transasia-xl200-biochem',
    brand: 'Transasia',
    model: 'XL 200 (Biochem)',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'LDH', 'AMYL'],
  },
  {
    id: 'transasia-chem7',
    brand: 'Transasia',
    model: 'Chem 7',
    category: 'Biochemistry',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['GLU', 'BUN', 'CREA', 'UA', 'TP', 'ALB', 'TBIL', 'DBIL', 'ALT', 'AST', 'ALP', 'GGT', 'CA', 'PHOS', 'K', 'NA', 'CL', 'TG', 'CHOL', 'HDL', 'LDL', 'CK', 'LDH', 'AMYL', 'LIPA', 'HbA1c'],
  },
  {
    id: 'roche-cobas-e411',
    brand: 'Roche',
    model: 'Cobas e411',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'TSH-3G', 'Vit-D', 'Vit-B12', 'Ferritin', 'Folate', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'CA15-3', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'Myoglobin', 'CK-MB-mass', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Homocysteine', 'Anti-TPO', 'Anti-Tg'],
  },
  {
    id: 'roche-cobas-e601',
    brand: 'Roche',
    model: 'Cobas e601',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'TSH-3G', 'Vit-D', 'Vit-B12', 'Ferritin', 'Folate', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'CA15-3', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'Myoglobin', 'CK-MB-mass', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Homocysteine', 'Anti-TPO', 'Anti-Tg', 'HIV-Ag', 'HBsAg', 'Anti-HCV', 'Anti-HIV'],
  },
  {
    id: 'abbott-architect-i1000',
    brand: 'Abbott',
    model: 'Architect i1000',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'HBsAg', 'Anti-HCV', 'Anti-HIV'],
  },
  {
    id: 'abbott-architect-i2000',
    brand: 'Abbott',
    model: 'Architect i2000',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'Vit-D', 'Vit-B12', 'Ferritin', 'Folate', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'CA15-3', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'Myoglobin', 'CK-MB-mass', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Homocysteine', 'Anti-TPO', 'Anti-Tg', 'HIV-Ag', 'HBsAg', 'Anti-HCV', 'Anti-HIV'],
  },
  {
    id: 'siemens-advia-centaur',
    brand: 'Siemens',
    model: 'Advia Centaur',
    category: 'Immunoassay',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'HBsAg', 'Anti-HCV', 'Anti-HIV', 'Anti-HBs'],
  },
  {
    id: 'siemens-immulite',
    brand: 'Siemens',
    model: 'Immulite 2000',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Ferritin', 'Vit-B12', 'Folate', 'Anti-TPO', 'Anti-Tg'],
  },
  {
    id: 'snibe-maglumi-800',
    brand: 'Snibe',
    model: 'Maglumi 800',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'TSH-3G', 'Vit-D', 'Vit-B12', 'Ferritin', 'Folate', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'CA15-3', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Homocysteine', 'Anti-TPO', 'Anti-Tg', 'HBsAg', 'Anti-HCV', 'Anti-HIV'],
  },
  {
    id: 'snibe-maglumi-2000',
    brand: 'Snibe',
    model: 'Maglumi 2000',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'TSH-3G', 'Vit-D', 'Vit-B12', 'Ferritin', 'Folate', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'CA15-3', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Insulin', 'C-Peptide', 'Testosterone', 'Estradiol', 'Progesterone', 'DHEA-S', 'Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Homocysteine', 'Anti-TPO', 'Anti-Tg', 'HBsAg', 'Anti-HCV', 'Anti-HIV', 'HIV-Ag'],
  },
  {
    id: 'mindray-cl2000i',
    brand: 'Mindray',
    model: 'CL-2000i',
    category: 'Immunoassay',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'TSH-3G', 'Vit-D', 'Vit-B12', 'Ferritin', 'Folate', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'CA15-3', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'HBsAg', 'Anti-HCV', 'Anti-HIV'],
  },
  {
    id: 'erba-mannheim-clia',
    brand: 'Erba',
    model: 'Mannheim CLIA',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['TSH', 'T3', 'T4', 'FT3', 'FT4', 'PSA', 'Free-PSA', 'AFP', 'CEA', 'CA125', 'CA19-9', 'Beta-hCG', 'hCG', 'Prolactin', 'Cortisol', 'Ferritin', 'Vit-B12', 'Folate', 'Troponin-I', 'D-Dimer', 'CRP-hs', 'HBsAg', 'Anti-HCV', 'Anti-HIV'],
  },
  {
    id: 'getein-1160',
    brand: 'Getein',
    model: 'Getein 1160',
    category: 'Immunoassay',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['Troponin-I', 'NT-proBNP', 'D-Dimer', 'CRP-hs', 'Myoglobin', 'CK-MB-mass', 'Lp-PLA2', 'S100', 'KAP', 'LAMBDA'],
  },

  // ========================== ELECTROLYTE / BLOOD GAS ==========================
  {
    id: 'erba-smart240',
    brand: 'Erba',
    model: 'Smart 240',
    category: 'Electrolyte',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['NA', 'K', 'CL', 'iCA', 'TCO2', 'AG'],
  },
  {
    id: 'mindray-bsa2400',
    brand: 'Mindray',
    model: 'BSA-2400',
    category: 'Electrolyte',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['NA', 'K', 'CL', 'iCA', 'TCO2'],
  },
  {
    id: 'siemens-rapidlab1200',
    brand: 'Siemens',
    model: 'RAPIDLab 1200',
    category: 'Blood Gas',
    protocol: 'proprietary',
    transport: 'serial',
    direction: 'bi',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['pH', 'pCO2', 'pO2', 'Na', 'K', 'iCa', 'Cl', 'Glu', 'Lac', 'Hct', 'Hb', 'sO2', 'TCO2', 'BE', 'HCO3'],
  },
  {
    id: 'nova-biomedical-statprofile',
    brand: 'Nova Biomedical',
    model: 'Stat Profile Prime',
    category: 'Blood Gas',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['pH', 'pCO2', 'pO2', 'Na', 'K', 'iCa', 'Cl', 'Glu', 'Lac', 'Hct', 'Hb', 'sO2', 'TCO2', 'BE', 'HCO3', 'Creat'],
  },

  // ========================== URINE ANALYZERS ==========================
  {
    id: 'mindray-ua60',
    brand: 'Mindray',
    model: 'UA-60',
    category: 'Urine',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['URO', 'BIL', 'KET', 'BLD', 'PRO', 'NIT', 'LEU', 'GLU', 'pH', 'SG', 'VC', 'COLOR', 'CLA'],
  },
  {
    id: 'mindray-ua600',
    brand: 'Mindray',
    model: 'UA-600',
    category: 'Urine',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['URO', 'BIL', 'KET', 'BLD', 'PRO', 'NIT', 'LEU', 'GLU', 'pH', 'SG', 'VC', 'COLOR', 'CLA'],
  },
  {
    id: 'erba-urine240',
    brand: 'Erba',
    model: 'Urine 240',
    category: 'Urine',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['URO', 'BIL', 'KET', 'BLD', 'PRO', 'NIT', 'LEU', 'GLU', 'pH', 'SG', 'VC'],
  },
  {
    id: 'sysmex-uf1000i',
    brand: 'Sysmex',
    model: 'UF-1000i',
    category: 'Urine',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['RBC-U', 'WBC-U', 'EC', 'BACT', 'HYAL', 'CAST', 'CRYSTAL', 'YLC', 'SRC', 'MUCUS', 'Cond', 'OSMO'],
  },
  {
    id: 'arkray-ax4030',
    brand: 'Arkray',
    model: 'AX-4030',
    category: 'Urine',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['URO', 'BIL', 'KET', 'BLD', 'PRO', 'NIT', 'LEU', 'GLU', 'pH', 'SG', 'VC', 'COLOR', 'CLA'],
  },

  // ========================== COAGULATION ==========================
  {
    id: 'sysmex-cs5100',
    brand: 'Sysmex',
    model: 'CS-5100',
    category: 'Coagulation',
    protocol: 'hl7',
    transport: 'tcp',
    direction: 'bi',
    tcpPort: 5000,
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['PT', 'INR', 'APTT', 'FIB', 'TT', 'D-Dimer', 'FDP', 'AT-III', 'Protein-C', 'Protein-S', 'Lupus-Anticoagulant'],
  },
  {
    id: 'erba-cl50',
    brand: 'Erba',
    model: 'CL-50',
    category: 'Coagulation',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['PT', 'INR', 'APTT', 'FIB', 'TT'],
  },
  {
    id: 'mindray-cl2000',
    brand: 'Mindray',
    model: 'CL-2000',
    category: 'Coagulation',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['PT', 'INR', 'APTT', 'FIB', 'TT', 'D-Dimer'],
  },

  // ========================== ELISA / MICROPLATE ==========================
  {
    id: 'bio-rad-680',
    brand: 'Bio-Rad',
    model: 'Model 680',
    category: 'ELISA',
    protocol: 'file',
    transport: 'file',
    direction: 'uni',
    tests: ['HIV', 'HBsAg', 'Anti-HCV', 'Anti-HBs', 'Dengue-IgM', 'Dengue-IgG', 'TyphiDot-IgM', 'TyphiDot-IgG', 'Leptospira-IgM', 'Brucella-IgM', 'Cardiolipin-IgG', 'Cardiolipin-IgM', 'Beta-2-GPI-IgG', 'Beta-2-GPI-IgM'],
  },
  {
    id: 'thermo-multiskan',
    brand: 'Thermo Fisher',
    model: 'Multiskan FC',
    category: 'ELISA',
    protocol: 'file',
    transport: 'file',
    direction: 'uni',
    tests: ['HIV', 'HBsAg', 'Anti-HCV', 'Anti-HBs', 'Dengue-IgM', 'Dengue-IgG', 'TyphiDot-IgM', 'TyphiDot-IgG', 'Leptospira-IgM', 'Brucella-IgM'],
  },
  {
    id: 'erba-elisa-reader',
    brand: 'Erba',
    model: 'ELISA Reader',
    category: 'ELISA',
    protocol: 'file',
    transport: 'file',
    direction: 'uni',
    tests: ['HIV', 'HBsAg', 'Anti-HCV', 'Anti-HBs', 'Dengue-IgM', 'Dengue-IgG', 'TyphiDot-IgM', 'TyphiDot-IgG'],
  },

  // ========================== HbA1c / SPECIALIZED ==========================
  {
    id: 'bio-rad-d10',
    brand: 'Bio-Rad',
    model: 'D-10',
    category: 'HbA1c',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['HbA1c', 'HbA2', 'HbF', 'Hb-Total', 'Hb-Variant'],
  },
  {
    id: 'trivitron-hb1c',
    brand: 'Trivitron',
    model: 'HbA1c Analyzer',
    category: 'HbA1c',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['HbA1c'],
  },
  {
    id: 'mindray-ba88a',
    brand: 'Mindray',
    model: 'BA-88A',
    category: 'HbA1c',
    protocol: 'astm',
    transport: 'serial',
    direction: 'uni',
    serialSettings: { baudRate: 9600, dataBits: 8, parity: 'none', stopBits: 1 },
    tests: ['HbA1c', 'Hb', 'HbA2', 'HbF'],
  },
];

// Group by category for UI
function getByCategory() {
  const grouped = {};
  for (const a of ANALYZERS) {
    if (!grouped[a.category]) grouped[a.category] = [];
    grouped[a.category].push(a);
  }
  return grouped;
}

// Get by brand
function getByBrand() {
  const grouped = {};
  for (const a of ANALYZERS) {
    if (!grouped[a.brand]) grouped[a.brand] = [];
    grouped[a.brand].push(a);
  }
  return grouped;
}

// Find by id
function getById(id) {
  return ANALYZERS.find(a => a.id === id);
}

// Get all brands
function getBrands() {
  return [...new Set(ANALYZERS.map(a => a.brand))].sort();
}

// Get all categories
function getCategories() {
  return [...new Set(ANALYZERS.map(a => a.category))].sort();
}

module.exports = {
  ANALYZERS,
  getByCategory,
  getByBrand,
  getById,
  getBrands,
  getCategories,
};
